- languages/wp-maintenance-mode-it_IT.po
I have done a new translation from scratch.
I hope that should be useful and included in next plugin release.
Bye
> New translation to for WP Maintenance Mode 2.0.3

- includes/classes/wp-maintenance-mode.php
> Add support for custom tpl view in theme folder

- includes/classes/wp-maintenance-mode.php
https://wordpress.org/support/topic/notice-undefined-index-status_data-in-wp-maintenance-mode-php-on-line-531/
> Solve undefined notice

- includes/classes/wp-maintenance-mode.php
- includes/functions/helpers.php
- includes/functions/hooks.php
- views/maintenance.php
- wp-maintenance-mode.php
1. replace create_function; solves #186 issue and [ticket](https://wordpress.org/support/topic/create_function-deprecated-in-php-7-2-8/)
2. solve "set options on first activation" bug [ticket](https://wordpress.org/support/topic/notice-undefined-index-general-in-srv-www-mysite-test-current/)
3. make (frontend) privacy labels clickable
> Some fixes

- includes/classes/wp-maintenance-mode-admin.php
- includes/classes/wp-maintenance-mode.php
- views/google-analytics.php
- views/settings.php
> migrate to gtag and add anonymize_ip option

- includes/classes/wp-maintenance-mode.php
- views/maintenance.php
1. Fix PHP notice
> PHP Notice:  Undefined index: HTTP_USER_AGENT in [redacted]/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php on line 723
2. Solve issue #200
> fix php notice and add charset meta tag

- includes/classes/wp-maintenance-mode-admin.php
- includes/classes/wp-maintenance-mode.php
- includes/functions/helpers.php
- views/maintenance.php
- views/settings.php
> add privacy policy link target + fix to accept links inside gdpr textareas

- includes/classes/wp-maintenance-mode.php
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- .github/workflows/new-issues.yml
- CHANGELOG.md
- README.md
- composer.json
- includes/classes/wp-maintenance-mode.php
- package.json
- readme.txt
- views/maintenance.php
- wp-maintenance-mode.php
- language attribute added
- zoom enabled
- main landmark on wrap div
> Ref #296 Accessibility issues on the maintenance page

- includes/classes/wp-maintenance-mode.php
> Otter form save subscriber entry

- includes/classes/wp-maintenance-mode.php
- views/settings.php
> Fix PHP errors

- includes/classes/wp-maintenance-mode.php
> Fix maintenance mode issue for previously logged users

- views/maintenance.php
> Fix render embed shortcode

- includes/classes/wp-maintenance-mode.php
- views/settings.php
I'd like to be able to have comments in the exclude textarea, so I can comment the IP addresses for location.
Eg:
```
127.0.0.1 # localhost
140.82.121.4 # Github
#::1 # disabled item
```
> Allow for comments in exclude textarea

- includes/classes/wp-maintenance-mode.php
- views/maintenance.php
- views/wpmm-page-template.php
> Fixed the template override issue

- includes/classes/wp-maintenance-mode-admin.php
> Changed plugin name in the settings page

- includes/classes/wp-maintenance-mode-admin.php
> Fixed compatibility issue with PHP 5.6 and 8.0

- composer.json
- composer.lock
- includes/classes/wp-maintenance-mode-admin.php
- includes/classes/wp-maintenance-mode.php
- includes/functions/helpers.php
- wp-maintenance-mode.php
> Added about page integration

- includes/classes/wp-maintenance-mode.php
> Fixed compatibility issue with WP 6.4 RC2

- assets/css/style-admin.css
> Fixed broken templates layout issue

- .github/workflows/test-php.yml
- includes/classes/wp-maintenance-mode.php
- views/wpmm-page-template.php
In this PR I've fixed the compatibility issue with the Elementor plugin.
Closes #441
> Fixed compatibility issue with Elementor

- includes/classes/wp-maintenance-mode-admin.php
Resolved style conflict issue on the WPForms dashboard.
Closes https://github.com/Codeinwp/wp-maintenance-mode/issues/452
> Fixed conflict with WPForms

- assets/js/scripts-admin.js
- includes/classes/wp-maintenance-mode-admin.php
- views/wizard.php
This reverts the changes to remove the Hyve promo from TPC as part of https://github.com/Codeinwp/hyve/issues/24
> Remove Hyve Promo
